# Generated by Django 3.1.2 on 2021-07-31 01:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id_task', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fixed', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('note', models.CharField(max_length=255)),
                ('created_in', models.DateTimeField(auto_now_add=True)),
                ('closed_in', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('1', 'Planejada'), ('2', 'Em Execução'), ('3', 'Concluída'), ('4', 'Cancelada')], max_length=1)),
                ('situation', models.CharField(choices=[('1', 'Aberta'), ('2', 'Abandonada'), ('3', 'Fechada')], max_length=1)),
                ('priority', models.CharField(choices=[(0, 'Baixa'), (1, 'Normal'), (2, 'Alta')], max_length=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
